default_platform(:ios)

XCODEPROJ = "TrackPaw.xcodeproj"
SCHEME = "TrackPaw"

platform :ios do
  def asc_api_key
    app_store_connect_api_key(
      key_id: "***REMOVED***",
      issuer_id: "***REMOVED***",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_***REMOVED***.p8"),
      in_house: false
    )
  end

  desc "Build and upload a new beta build to TestFlight"
  lane :beta do
    api_key = asc_api_key

    increment_build_number(
      xcodeproj: XCODEPROJ,
      build_number: (latest_testflight_build_number(api_key: api_key, initial_build_number: 0) + 1).to_s
    )

    build_app(
      scheme: SCHEME,
      export_method: "app-store",
      output_directory: "./build",
      xcargs: "-allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )

    add_git_tag(tag: "#{get_version_number(xcodeproj: XCODEPROJ, target: SCHEME)}(#{get_build_number(xcodeproj: XCODEPROJ)})")
  end
end
