import XCTest

@MainActor
final class ScreenshotTests: XCTestCase {
    override func setUpWithError() throws {
        continueAfterFailure = false
    }

    func testScreenshotFlow() throws {
        // This test depends on a simulated GPS walk fed to the Simulator from
        // outside the test process by the `screenshots` lane (see Fastfile) —
        // a plain `xcodebuild test` never starts that walk, so the "Start"
        // marker assertion below would fail every time. `TEST_RUNNER_SCREENSHOT_LANE`
        // is set by the lane and arrives here (per Xcode's `TEST_RUNNER_`
        // convention) as `SCREENSHOT_LANE`. Run `fastlane screenshots` to
        // exercise this test for real.
        try XCTSkipIf(
            ProcessInfo.processInfo.environment["SCREENSHOT_LANE"] == nil,
            "Screenshots are generated by `fastlane screenshots`, which simulates the GPS walk this test needs — run that lane to execute this test."
        )

        let app = XCUIApplication()
        // Pin the system language/region so localized strings (the section
        // header, "Name" field placeholder, etc.) render in English regardless
        // of the host machine's simulator locale — required for this test to be
        // deterministic across machines, and for screenshot automation in
        // general to produce a known-language result.
        app.launchArguments = ["-SNAPSHOT", "-AppleLanguages", "(en)", "-AppleLocale", "en_US"]
        setupSnapshot(app)
        app.launch()

        XCTAssertTrue(app.staticTexts["Morning walk with Bella"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.staticTexts["Forest scent trail"].exists)
        XCTAssertTrue(app.buttons["addTrackButton"].exists)

        // Both fixtures are seeded with state = .trailTracked, so they must land
        // under a single "Finished tracks" section with no duplicates.
        XCTAssertEqual(app.buttons.matching(identifier: "trackCell").count, 2)
        XCTAssertTrue(app.staticTexts["Finished tracks"].exists)
        snapshot("01TrackList")

        app.buttons["trackCell"].firstMatch.tap()
        XCTAssertTrue(app.navigationBars.staticTexts.firstMatch.waitForExistence(timeout: 5))
        XCTAssertTrue(app.textFields["Name"].waitForExistence(timeout: 5))
        snapshot("02EditTrack")

        // EditTrackView's trailing toolbar holds three items (including a ShareLink),
        // so an index-based lookup for the back button is one tap away from hitting
        // one of those instead. The back button inherits TrackListView's
        // navigationTitle("Tracks"), which is deterministic since the language is
        // pinned above.
        app.navigationBars.buttons["Tracks"].tap() // back to the list

        // The location permission prompt is granted ahead of time by the
        // `screenshots` lane (`xcrun simctl privacy ... grant location-always`),
        // which skips the system alert entirely — this makes the flow immune
        // to the Simulator's system language, unlike matching on button
        // labels. This monitor stays only as a fallback for local runs (e.g.
        // `xcodebuild test` directly) where that pre-grant step hasn't run and
        // the alert still appears in English or Swedish.
        addUIInterruptionMonitor(withDescription: "Location permission") { alert in
            for label in ["Allow While Using App", "Allow Once", "Allow",
                          "Tillåt medan appen används", "Tillåt en gång", "Tillåt"] {
                let button = alert.buttons[label]
                if button.exists {
                    button.tap()
                    return true
                }
            }
            return false
        }

        // The walk itself is driven from outside this test process, by the
        // `screenshots` lane feeding a continuous route to the Simulator via
        // `xcrun simctl location ... start` for the whole test suite (see
        // the Fastfile) — independent of this test's automation session.
        app.buttons["addTrackButton"].tap()
        app.tap() // wake the interruption monitor so it can dismiss the system alert

        let startButton = app.buttons["startTrackingButton"]
        XCTAssertTrue(startButton.waitForExistence(timeout: 10))
        startButton.tap()
        sleep(20) // let the ambient walk advance far enough to draw a visible path

        // `trailStartLocation` (and the "Start" marker rendered from it) is
        // only set from a real CLLocation fix delivered to TrackMapModel —
        // it's absent if the lane's simulated walk never reached the
        // simulator in time, which would otherwise let a pathless map
        // through to the screenshot silently.
        XCTAssertTrue(app.otherElements["Start"].waitForExistence(timeout: 5),
                      "No location fix arrived — the route was not drawn")
        XCTAssertTrue(app.buttons["Pause"].waitForExistence(timeout: 5))
        snapshot("03LiveTracking")
    }
}
